version: "3.7"
services:
   server:
      image: omaxanderson/group-listen:latest
      ports:
         - "3000:3000"
      environment:
         - MYSQL_DB_USERNAME=username
         - MYSQL_DB_PASSWORD=password
