apiVersion: v1
kind: Service
metadata:
   name: group-listen-service
spec:
   selector:
      app: group-listen
   ports:
      - protocol: TCP
        port: 3000
        targetPort: 3000
   type: NodePort
