version: 2
jobs:
   build_server:
      working_directory: ~/app
      docker:
         - image: circleci/node:4.8.2
      steps:
         - checkout
         - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
         - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
         - run:
            name: install-npm
            command: npm install
         - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
               - ./node_modules
         - run:
            name: my_command
            command: echo "Hello world"
workflows:
   version: 2
   build_that_server:
      jobs:
         - build_server
