version: 2
executors:
   node:
      working_directory: ~/app
      docker:
         - image: circleci/node:10.15.3
jobs:
   build_server:
      executor: node
      steps:
         - checkout
         - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
         - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
         - run:
            name: install-npm
            command: npm install
         - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
               - ./node_modules
   test:
      steps:
         - run:
            name: test
            command: npm run test
workflows:
   version: 2
   build_that_server:
      jobs:
         - build_server
         - test:
            requires:
               - build_server
