version: 2.1
executors:
   node:
      working_directory: ~/app
      docker:
         - image: circleci/node:10.15.3
      shell: /bin/bash
jobs:
   build_server:
      executor: node
      steps:
         - checkout
         - run:
            name: update-npm
            command: 'sudo npm install -g npm@latest'
         - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
         - run:
            name: install-npm
            command: npm install
         - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
               - ./node_modules
         - persist_to_workspace:
            root: ~/app
            paths:
               - .
   test:
      executor: node
      steps:
         - attach_workspace:
            at: ~/app
         - run:
            name: test
            command: npm run test
workflows:
   version: 2
   build_that_server:
      jobs:
         - build_server
         - test:
            requires:
               - build_server
